export const partOne = 'MyBord is built with TypeScript using GraphQL and'
  + ' [Apollo](https://www.apollographql.com/) on'
  + ' top of Node.js and React.'
  + '\n\n'
  + 'The front end client uses'
  + ' [React\'s experimental concurrent mode](https://reactjs.org/docs/concurrent-mode-intro.html).'
  + ' Other apis include [Framer Motion](https://www.framer.com/motion/) for fluid component'
  + ' animations, [Lottie](https://airbnb.io/lottie/#/) to render animated illustrations,'
  + ' and [Storybook](https://storybook.js.org/) for prototyping. [Ant Design](https://ant.design/)'
  + ' is used for a couple common components (though more and more are getting custom built)'
  + ' and we use [Nucleo](https://nucleoapp.com/) for most of our icons. Lastly, everything gets'
  + ' styled with Less and CSS Modules and testing is done with Enzyme.';

export const partTwo = 'The back end is written on top of Node.js and Express and specifically uses'
  + ' [Apollo Server](https://www.apollographql.com/docs/apollo-server/v1/servers/express/).'
  + ' We run a PostgreSQL database with a [Prisma](https://www.prisma.io/) ORM.'
  + ' [Passport.js](http://www.passportjs.org/) is used to manage authentication. Third party apis'
  + ' include'
  + ' [Google\'s Node.js Client Api](https://github.com/googleapis/google-api-nodejs-client#google-apis-nodejs-client).'
  + '\n\n'
  + 'Our servers are hosted via Heroku and are managed with [Prisma Cloud](https://www.prisma.io/cloud).'
  + ' Virtualization is done with Docker and Circle CI is used for CD management.';

export const partThree = 'Lastly, something to mention: at first, when you build an app, you think'
  + ' "Fantastic! I\'ll build this with complete test coverage. Unit tests, integration tests,'
  + ' end to end tests and more! I\'ll prototype every component in Storybook and make sure I have'
  + ' full accessibility coverage, performance optimization and everything I can think of!" At first,'
  + ' the ambitions were high, but as all of us developers know, there are always priorities to'
  + ' deliver on for an MVP and not everything can be done if you want to make progress'
  + ' and ship. So while those priorities are important to us'
  + ' as we want Jest, Enzyme, Storybook and more to be part of the core development process for'
  + ' MyBord, we\'re a bit more lean at the moment and are trying to get new features out the door.'
  + ' Important roadmap features include building out more tools and apis for each user\'s "bord",'
  + ' social media enhancements (following friends, subscribing, copying cards, trending), adding'
  + ' a browser extension, building a React Native app (and thus converting the codebase from React'
  + ' to React Native), enhanced OAuth, and possibly moving from Heroku to AWS.';
