version: 2.1
commands:
  install_deps:
    description: "Install the dependencies"
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
jobs:
  tests:
    working_directory: ~/bei-bei
    docker:
      - image: circleci/node:10
    steps:
      - install_deps
      - run:
          name: Run Tests
          command: yarn test --maxWorkers=1
  build:
    working_directory: ~/bei-bei
    docker:
      - image: circleci/node:10
    steps:
      - install_deps
      - run:
          name: Run Build
          command: yarn build:prod

workflows:
  version: 2.1
  all:
    jobs:
      - build
      - tests
