export const lorem = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.';

export const loremIpsum = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';

export const loremIpsumLong = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat pretium nibh ipsum consequat nisl. In massa tempor nec feugiat nisl pretium. Pellentesque massa placerat duis ultricies lacus sed. Tortor posuere ac ut consequat semper viverra nam libero. Sed sed risus pretium quam vulputate dignissim suspendisse. Pellentesque habitant morbi tristique senectus et netus et. Vitae et leo duis ut diam quam. Ut ornare lectus sit amet est. Iaculis urna id volutpat lacus laoreet.

Turpis egestas sed tempus urna et pharetra pharetra massa. Nunc sed augue lacus viverra vitae congue eu consequat. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. Adipiscing commodo elit at imperdiet dui accumsan sit amet nulla. Mattis molestie a iaculis at erat pellentesque. At imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Massa tempor nec feugiat nisl pretium fusce id velit ut. Urna et pharetra pharetra massa. Nisl vel pretium lectus quam id leo in. Ultrices sagittis orci a scelerisque purus semper eget duis. Dictum at tempor commodo ullamcorper a lacus vestibulum sed arcu. Blandit libero volutpat sed cras ornare arcu dui vivamus. In massa tempor nec feugiat nisl pretium fusce id. A diam maecenas sed enim ut sem viverra aliquet eget. Feugiat in fermentum posuere urna nec tincidunt praesent.

Duis tristique sollicitudin nibh sit amet commodo nulla. Donec massa sapien faucibus et molestie. Porttitor leo a diam sollicitudin tempor id eu nisl. Semper viverra nam libero justo laoreet sit amet cursus. Non enim praesent elementum facilisis leo vel fringilla est ullamcorper. Tempus egestas sed sed risus pretium quam. Enim diam vulputate ut pharetra sit amet aliquam id. Ornare lectus sit amet est placerat in egestas erat. Nisl purus in mollis nunc. Vestibulum lectus mauris ultrices eros in cursus turpis. Turpis massa tincidunt dui ut ornare. Gravida arcu ac tortor dignissim convallis aenean. Tempus urna et pharetra pharetra massa. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. At tempor commodo ullamcorper a lacus vestibulum. Ornare arcu odio ut sem. Mattis enim ut tellus elementum sagittis vitae et leo duis.

Bibendum enim facilisis gravida neque convallis a. Morbi tristique senectus et netus. Leo integer malesuada nunc vel risus. Magna fringilla urna porttitor rhoncus dolor purus. Diam vulputate ut pharetra sit. Accumsan tortor posuere ac ut consequat semper viverra nam. Facilisi nullam vehicula ipsum a arcu. Id nibh tortor id aliquet lectus proin nibh. Aliquam sem fringilla ut morbi. Fermentum et sollicitudin ac orci phasellus. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Hendrerit gravida rutrum quisque non tellus orci ac. Scelerisque felis imperdiet proin fermentum leo vel orci porta. Volutpat lacus laoreet non curabitur gravida. Maecenas accumsan lacus vel facilisis volutpat. Ut consequat semper viverra nam.

Ipsum a arcu cursus vitae congue. Convallis tellus id interdum velit laoreet. Arcu risus quis varius quam quisque. Dictum varius duis at consectetur lorem donec massa sapien faucibus. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Felis eget nunc lobortis mattis. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet. Tristique magna sit amet purus. Accumsan sit amet nulla facilisi morbi tempus. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Dictum varius duis at consectetur lorem donec massa. Neque gravida in fermentum et. Amet nisl purus in mollis nunc sed id. Rhoncus urna neque viverra justo nec ultrices dui sapien. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Morbi tincidunt ornare massa eget. Neque gravida in fermentum et. Blandit cursus risus at ultrices mi tempus.
`;
